version: "3.9"
services:
 php:
   build: .
   volumes:
    - ./www:/var/www
   healthcheck:
      test: ["CMD-SHELL", " curl http://nginx | grep works"]
      interval: 5s
      timeout: 5s
      retries: 5

 nginx:
    image: nginx:1.13
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./www:/var/www
      - ./nginx/:/etc/nginx/conf.d/